name: 'List Merged Pull Requests'
author: 'Tatsuya "Nari" Iwanari <tatsuyaw0c@gmail.com>'
description: 'List merged pull requests on the source branch'
branding:
  icon: 'list'
  color: 'white'
inputs:
  token:
    description: The GitHub Access Token
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
